# Generated by Django 4.0.4 on 2022-05-25 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familiares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=20)),
                ('DNI', models.IntegerField(unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
